VAR ANNO_PROCESO_      NUMBER; 
VAR NUMEMP_            NUMBER; 
VAR COD_MARIA_PINTO    NUMBER; 
VAR COD_CURACAVI       NUMBER; 
VAR COD_TALAGANTE      NUMBER; 
VAR COD_EL_MONTE       NUMBER; 
VAR COD_BUIN           NUMBER; 
VAR MOV_AD_MARIA_PINTO NUMBER; 
VAR MOV_AD_CURACAVI    NUMBER; 
VAR MOV_AD_TALAGANTE   NUMBER; 
VAR MOV_AD_EL_MONTE    NUMBER; 
VAR MOV_AD_BUIN        NUMBER;


EXEC :ANNO_PROCESO_      := 2020; 
EXEC :NUMEMP_            := 12868553; 
EXEC :COD_MARIA_PINTO    := 117; 
EXEC :COD_CURACAVI       := 118; 
EXEC :COD_TALAGANTE      := 119; 
EXEC :COD_EL_MONTE       := 120; 
EXEC :COD_BUIN           := 121; 
EXEC :MOV_AD_MARIA_PINTO := 20000; 
EXEC :MOV_AD_CURACAVI    := 25000; 
EXEC :MOV_AD_TALAGANTE   := 30000; 
EXEC :MOV_AD_EL_MONTE    := 35000; 
EXEC :MOV_AD_BUIN        := 40000; 


DECLARE 
v_DVRUN_           VARCHAR2(1); 
v_NOMBRE_EMPLEADO_ VARCHAR2(200); 
v_SUELDO           NUMBER(10); 
v_ID_COMUNA_       NUMBER(3); 
v_PMN              NUMBER; 
v_VMN              NUMBER; 
v_VMA              NUMBER; 
v_VTM              NUMBER; 


BEGIN 
SELECT dvrun_emp,pnombre_emp||' '||NVL(snombre_emp,'')||' '||appaterno_emp||' '||apmaterno_emp,sueldo_base, id_comuna 
INTO v_DVRUN_, v_NOMBRE_EMPLEADO_,v_SUELDO,v_ID_COMUNA_ 
FROM EMPLEADO 
WHERE numrun_emp = :NUMEMP_;
--PORCENTAJE MOVILIZACION NORMAL
v_PMN := TRUNC(v_SUELDO/100000); 
--VALOR MOVILIZACION NORMAL
v_VMN := v_SUELDO*(v_PMN/100);
--VALOR MOVILIZACION ADICIONAL
CASE 
WHEN v_ID_COMUNA_ = :COD_MARIA_PINTO THEN v_VMA := :MOV_AD_MARIA_PINTO; 
WHEN v_ID_COMUNA_ = :COD_CURACAVI    THEN v_VMA := :MOV_AD_CURACAVI ; 
WHEN v_ID_COMUNA_ = :COD_TALAGANTE   THEN v_VMA := :MOV_AD_TALAGANTE; 
WHEN v_ID_COMUNA_ = :COD_EL_MONTE    THEN v_VMA := :MOV_AD_EL_MONTE; 
WHEN v_ID_COMUNA_ = :COD_BUIN        THEN v_VMA := :MOV_AD_BUIN; 
ELSE v_VMA := 0; 
END CASE; 
--VALOR TOTAL MOVIL 
v_VTM := v_VMN + v_VMA; 


INSERT INTO PROY_MOVILIZACION(
ANNO_PROCESO,
NUMRUN_EMP,
DVRUN_EMP,
NOMBRE_EMPLEADO,
SUELDO_BASE,
PORC_MOVIL_NORMAL,
VALOR_MOVIL_NORMAL,
VALOR_MOVIL_EXTRA,
VALOR_TOTAL_MOVIL)


VALUES(
:ANNO_PROCESO_,
:NUMEMP_,
v_DVRUN_,
v_NOMBRE_EMPLEADO_,
v_SUELDO,
v_PMN,
v_VMN,
v_VMA,
v_VTM);
COMMIT;
END;
